"""Initial migration with Users Table

Revision ID: e5ef929dfc70
Revises: 
Create Date: 2024-09-26 12:48:02.926361

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ef929dfc70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.String(length=255), nullable=False),
    sa.Column('email', sqlmodel.String(length=255), nullable=False),
    sa.Column('gender', sqlmodel.String(length=10), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('diet_type', sqlmodel.String(length=20), nullable=False),
    sa.Column('password', sqlmodel.String(length=255), nullable=False),
    sa.Column('confirm_password', sqlmodel.String(length=255), nullable=False),
    sa.Column('user_role', sqlmodel.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
